## Numpy

NumPy es fundamental en Python para computación científica y análisis de datos. Sus funciones clave permiten crear, manipular y operar eficientemente con arrays n-dimensionales (ndarrays)

Partimos por importar numpy

In [639]:
import numpy as np

### Arrays

Creamos una lista y la transformamos en array. Estos son estructuras de datos homogéneas, multidimensionales y de tamaño fijo.

In [660]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Si trato de crear una con otro tipo de dato, por ejemplo, agregar una string, numpy transforma todo el array a dtype string.

In [663]:
np.array([1, 2, 3, 4, "gato"])

array(['1', '2', '3', '4', 'gato'], dtype='<U21')

Si introduzco un número decimal, transforma todo el array en float.

In [665]:
np.array([1.1, 2, 3.4, 4, 5])

array([1.1, 2. , 3.4, 4. , 5. ])

Podemos generar algunos arrays o matrices definiendo sus tamaños. 

Por ejemplo, una matriz de 1s o 0s.

In [643]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [644]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Un array que cubra un espacio homogeneamente.

In [ ]:
np.linspace(0, 10, 101) #En linspace, el último número es el número de elementos.

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

O por otro lado, un array que tenga elementos x-espaciados.

In [668]:
np.arange(0, 5, 0.1) #En arange, el último número es tamaño del paso.

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

Podemos generar una matriz de números aleatorios

In [671]:
data = np.random.randn(5, 4) #La matriz tiene 5 filas y 5 columnas.
data

array([[-0.7133761 , -0.01323753, -1.17569064,  1.05903407],
       [ 0.41284302, -0.77869408,  0.71504817, -0.20066234],
       [-0.62094652, -1.3146927 ,  1.33649426,  1.015081  ],
       [ 0.0231844 , -0.52156973, -0.43349932,  0.92969767],
       [ 0.59428787,  0.78760157,  0.91852964, -0.09591682]])

Podemos cambiar el la forma de la matriz

In [ ]:
data.reshape(2, 10) #Ahora la matriz tiene 2 filas y 10 columnas.

array([[-0.7133761 , -0.01323753, -1.17569064,  1.05903407,  0.41284302,
        -0.77869408,  0.71504817, -0.20066234, -0.62094652, -1.3146927 ],
       [ 1.33649426,  1.015081  ,  0.0231844 , -0.52156973, -0.43349932,
         0.92969767,  0.59428787,  0.78760157,  0.91852964, -0.09591682]])

Se pueden concatenar matrices y arrays en sus diferentes ejes

In [675]:
np.concatenate((data, data), axis = 0)

array([[-0.7133761 , -0.01323753, -1.17569064,  1.05903407],
       [ 0.41284302, -0.77869408,  0.71504817, -0.20066234],
       [-0.62094652, -1.3146927 ,  1.33649426,  1.015081  ],
       [ 0.0231844 , -0.52156973, -0.43349932,  0.92969767],
       [ 0.59428787,  0.78760157,  0.91852964, -0.09591682],
       [-0.7133761 , -0.01323753, -1.17569064,  1.05903407],
       [ 0.41284302, -0.77869408,  0.71504817, -0.20066234],
       [-0.62094652, -1.3146927 ,  1.33649426,  1.015081  ],
       [ 0.0231844 , -0.52156973, -0.43349932,  0.92969767],
       [ 0.59428787,  0.78760157,  0.91852964, -0.09591682]])

In [676]:
np.concatenate((data, data), axis = 1)

array([[-0.7133761 , -0.01323753, -1.17569064,  1.05903407, -0.7133761 ,
        -0.01323753, -1.17569064,  1.05903407],
       [ 0.41284302, -0.77869408,  0.71504817, -0.20066234,  0.41284302,
        -0.77869408,  0.71504817, -0.20066234],
       [-0.62094652, -1.3146927 ,  1.33649426,  1.015081  , -0.62094652,
        -1.3146927 ,  1.33649426,  1.015081  ],
       [ 0.0231844 , -0.52156973, -0.43349932,  0.92969767,  0.0231844 ,
        -0.52156973, -0.43349932,  0.92969767],
       [ 0.59428787,  0.78760157,  0.91852964, -0.09591682,  0.59428787,
         0.78760157,  0.91852964, -0.09591682]])

Y podemos aplanar la matriz para generar un array de una dimensión

In [680]:
data.flatten() #Nos queda un array de una dimensión y 25 elementos.

array([-0.7133761 , -0.01323753, -1.17569064,  1.05903407,  0.41284302,
       -0.77869408,  0.71504817, -0.20066234, -0.62094652, -1.3146927 ,
        1.33649426,  1.015081  ,  0.0231844 , -0.52156973, -0.43349932,
        0.92969767,  0.59428787,  0.78760157,  0.91852964, -0.09591682])

### Estadísticas
Podemos hacer un poco de estadística descriptiva utilizando funciones de numpy

Por ejemplo, concocer el valor de la suma de nuestros datos

In [649]:
np.sum(data)

np.float64(-2.6108809291000146)

Promedio, desviación estandar y percentiles

In [650]:
np.mean(data, axis = 0)

array([-0.34665478, -0.38889649, -0.24093268,  0.11836045,  0.33594732])

In [651]:
np.std(data, axis = 0)

array([1.24351577, 0.84754466, 0.66690652, 0.79568011, 0.63137487])

In [652]:
q1 = np.quantile(data, 0.25) #Cuartil 1
median = np.quantile(data, 0.5) #Mediana
q3 = np.quantile(data, 0.75) #Cuartil 3
display(q1, median, q3)

np.float64(-0.6485411385129989)

np.float64(0.06814390282361403)

np.float64(0.2537684395265671)

### Algebra lineal


NumPy es la librería fundamental para el álgebra lineal en Python. Permite obtener operaciones extensivas en cálculos de forma eficiente.

In [704]:
matrix = np.array([[0.1, 0.5], [-0, -0.1]])
matrix

array([[ 0.1,  0.5],
       [ 0. , -0.1]])

Por ejemplo, obtener la inversa de una matrix

In [708]:
inverse = np.linalg.inv(matrix)
inverse

array([[ 10.,  50.],
       [ -0., -10.]])

Realizar multiplicaciones matriciales (un proceso bastante costoso computacionalmente).

In [ ]:
matrix@inverse #Nos da la matriz identidad.

array([[1., 0.],
       [0., 1.]])

Cálcular determinantes.

In [710]:
np.linalg.det(matrix)

np.float64(-0.010000000000000004)

Descomposiciones de matrices, obtención de vectores y valores propios:

In [711]:
eigenvectors, eigenvalues = np.linalg.eig(matrix)
display(eigenvectors, eigenvalues)

array([ 0.1, -0.1])

array([[ 1.        , -0.92847669],
       [ 0.        ,  0.37139068]])

O incluso Singular value decomposition.

In [714]:
U, s, V = np.linalg.svd(matrix)
display(U, s, V)

array([[ 0.98195639,  0.18910752],
       [-0.18910752,  0.98195639]])

array([0.51925824, 0.01925824])

array([[ 0.18910752,  0.98195639],
       [ 0.98195639, -0.18910752]])

Además, podemos utilizar numpy resolver sistemas de ecuaciones lineales.

In [712]:
np.linalg.solve(matrix, np.array([1, 1]))

array([ 60., -10.])